### ISSUE TITLE
关于 16.01.md Cond 的例子

### ISSUE THREAD

**Issue by lycheng** [polaris1119/The-Golang-Standard-Library-by-Example#24]
``` golang
package main

import (
    "fmt"
    "sync"
    "time"
)

var locker = new(sync.Mutex)
var cond = sync.NewCond(locker)

func test(x int) {

    cond.L.Lock() // 获取锁
    cond.Wait()   // 等待通知  暂时阻塞
    fmt.Println(x)
    time.Sleep(time.Second * 1)
    cond.L.Unlock() // 释放锁，不释放的话将只会有一次输出
}
func main() {
    for i := 0; i < 40; i++ {
        go test(i)
    }
    fmt.Println("start all")
    cond.Broadcast() //  下发广播给所有等待的goroutine
    time.Sleep(time.Second * 60)
}
```

我自己在试的时候发现 test 函数的并不能正常打印出结果。有时候没有输出，有时候输出很多。

我想问下这个是不是因为 goroutine 无序执行的原因？

**Comment by niyanchun** [comment]
@lycheng 我再Mac上面测试了一下这个程序，没有问题。但是在Ubuntu上面测会出现你说的这种问题，我debug了一下，看了一下调用栈：

(dlv) bt
0  0x0000000000453693 in runtime.futex
   at /usr/local/go/src/runtime/sys_linux_amd64.s:388
1  0x00000000004238de in runtime.futexsleep
   at /usr/local/go/src/runtime/os_linux.go:62
2  0x000000000040c370 in runtime.notetsleep_internal
   at /usr/local/go/src/runtime/lock_futex.go:174
3  0x000000000040c4e2 in runtime.notetsleepg
   at /usr/local/go/src/runtime/lock_futex.go:206
4  0x000000000043fff8 in runtime.timerproc
   at /usr/local/go/src/runtime/time.go:209
5  0x00000000004525f0 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:2086
(dlv) goroutine
Thread 9327 at /usr/local/go/src/runtime/sys_linux_amd64.s:388
Goroutine 15:
	Runtime: /usr/local/go/src/runtime/lock_futex.go:206 runtime.notetsleepg (0x40c4e2)
	User: /usr/local/go/src/runtime/lock_futex.go:206 runtime.notetsleepg (0x40c4e2)
	Go: /usr/local/go/src/runtime/time.go:97 runtime.addtimerLocked (0x43fc2e)
(dlv) goroutines
[15 goroutines]
  Goroutine 1 - User: /usr/local/go/src/runtime/time.go:59 time.Sleep (0x43fa55)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:260 runtime.gopark (0x4283fa)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:260 runtime.gopark (0x4283fa)
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:260 runtime.gopark (0x4283fa)
  Goroutine 5 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 6 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 7 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 8 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 9 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 10 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 11 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 12 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 13 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
  Goroutine 14 - User: /usr/local/go/src/runtime/sema.go:267 sync.runtime_notifyListWait (0x436341)
* Goroutine 15 - User: /usr/local/go/src/runtime/lock_futex.go:206 runtime.notetsleepg (0x40c4e2) 


有的goroutine卡在没有收到广播信号，所以我想问题出在当main goroutine执行`cond.Broadcast()`的时候，有的goroutine还没有执行到`cond.Wait()`。然后我测了一下，如果在main goroutine执行`cond.Broadcast()`前加上`time.Sleep`，保证所有的（当然不能完全保证）goroutine都运行到`cond.Wait()`，这样就不会出现上面的情况了。你可以试一下~

**Comment by lycheng** [comment]
是的，这个我自己测试的时候发现了

谢谢
