### ISSUE TITLE
chapter01/01.3.md 漏加代码框

### ISSUE THREAD

**Issue by caliburn1994** [polaris1119/The-Golang-Standard-Library-by-Example#33]
var ( name string age int ) n, _ := fmt.Sscan("polaris 28", &name, &age) // 可以将"polaris 28"中的空格换成"\n"试试 // n, _ := fmt.Sscan("polaris\n28", &name, &age) fmt.Println(n, name, age)

**Comment by caliburn1994** [comment]
var ( name string age int ) n, _ := fmt.Sscanf("polaris 28", "%s%d", &name, &age) // 可以将"polaris 28"中的空格换成"\n"试试 // n, _ := fmt.Sscanf("polaris\n28", "%s%d", &name, &age) fmt.Println(n, name, age)

**Comment by caliburn1994** [comment]
var ( name string age int ) n, _ := fmt.Sscanln("polaris 28", &name, &age) // 可以将"polaris 28"中的空格换成"\n"试试 // n, _ := fmt.Sscanln("polaris\n28", &name, &age) fmt.Println(n, name, age)

**Comment by polaris1119** [comment]
有啊
