### ISSUE TITLE
io.Close 章节关于 defer file.Close() 解释有问题吧？

### ISSUE THREAD

**Issue by isLishude** [polaris1119/The-Golang-Standard-Library-by-Example#40]
原文链接：https://books.studygolang.com/The-Golang-Standard-Library-by-Example/chapter01/01.1.html#closer%E6%8E%A5%E5%8F%A3

<img width="865" alt="2018-01-24 3 42 04" src="https://user-images.githubusercontent.com/24730006/35319998-2b086302-011d-11e8-890a-cd40c61120d3.png">

`defer file.Close()` 是在函数最后阶段执行，无论是放在错误检查前后行为都是一致的吧，不会有错误吧！？

求教。

**Comment by snaigle** [comment]
defer file.Close() 应该放到err检查之后

**Comment by isLishude** [comment]
@snaigle 这里调用的 `defer file.Close()` ，放在 err 检查的前后并没有什么区别的吧。

**Comment by polaris1119** [comment]
我确认了下，之所以在 error 之前 file.Close 没有问题，是因为 Close 的实现是这样的：

```go
func (f *File) Close() error {
  	if f == nil {
  		return ErrInvalid
  	}
  	return f.file.close()
 }
` ``

一般里说，对一个 nil 对象，调用它的方法，会出问题的。

但这块的解释，确实需要稍微改下。但先判断错误，在 defer file.Close() 绝对是正确的做法，养成这样的习惯吧。
